/*
** LAST UPDATED SOME POINT IN NOVEMBER 2019.
*/

/*MAIN USERS TABLE */
CREATE TABLE Users (
  UUID CHAR(36) NOT NULL PRIMARY KEY,
  Username VARCHAR(16) UNIQUE,
  IsAdmin BOOLEAN,
  PasswordHash CHAR(64),
  PasswordSalt CHAR(64)
);

/*ACCOUNT CREATION CODES*/
CREATE TABLE Codes (
  Code VARCHAR(16) NOT NULL UNIQUE,
  Valid BOOLEAN NOT NULL
);

/*LOG API CALLS*/
CREATE TABLE APILog (
  UUID CHAR(36),
  FOREIGN KEY (UUID) REFERENCES Users(UUID) ON DELETE CASCADE,
  IPAddress VARBINARY(16),
  Action VARCHAR(32) NOT NULL,
  Timestamp DATETIME NOT NULL
);
