/*
** LAST UPDATED 05/10/2019
*/

/*MAIN USERS TABLE */
CREATE TABLE Users (
  UUID CHAR(36) NOT NULL PRIMARY KEY,
  Username VARCHAR(16) UNIQUE,
  IsAdmin BOOLEAN,
  PasswordHash CHAR(64),
  PasswordSalt CHAR(64)
);

/*ACCOUNT CREATION CODES*/
CREATE TABLE Codes (
  Code VARCHAR(16) NOT NULL UNIQUE,
  Valid BOOLEAN NOT NULL
);
